Tests
mpa-mxiang/math-magician pull request #7
Opened 2023-06-07 21:37 UTC by MarcoDDM

2023-06-07 22:30 UTC, emmiiorji requested changes
Hi @MarcoDDM and Team, 
# Status: Changes Required ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/220869680-787a77f7-922b-4e57-8fa4-368533d83b89.gif'/>
</div>

## Good Highlights✔️

- Most of the calculator logic has been tested


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 22:30 UTC, emmiiorji commented on src/logic/calculate.js
> -    // If there is an operation, update next
[Optional] I don't think it was necessary to remove these comments since they're meaningful and help to understand the code better.

2023-06-07 22:30 UTC, emmiiorji commented on src/logic/calculate.test.js
> +    };
You have done great at writing the tests for the operate.js and calculate.js modules. Kindly ensure that all functionalities & scenarios of the calculate.js modules are covered.

2023-06-07 22:30 UTC, emmiiorji commented on src/index.js
>      <App />
As specified in the [requirements](https://github.com/microverseinc/curriculum-react-redux/blob/be3b13a85ca425c0bf0eeb1f130b6a52e36deb4f/math-magicians/project_tests.md?plain=1#L31), kindly ensure that you write unit tests for all the react components. You seem not to have tested any component.

Also, as [required](https://github.com/microverseinc/curriculum-react-redux/blob/be3b13a85ca425c0bf0eeb1f130b6a52e36deb4f/math-magicians/project_tests.md?plain=1#L34), kindly ensure that user interaction is simulated.

2023-06-08 21:36 UTC, levy002 approved these changes
## Hello @mpa-mxiang 
 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

  ![unnamed](https://github.com/HERMON-1995/OOP-school-library/assets/87197412/74ff9d90-dd35-49c7-9a85-e33a0ac154b7)


## Highlights
- No linter error :heavy_check_mark: 
- You implemented the suggested changes :heavy_check_mark: 
 
## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 21:54 UTC, mpa-mxiang commented
Thank you for the approval! @levy002

2023-06-08 21:54 UTC, merged